In [1]:
print('Hello I am excited to learn pyTorch!')

Hello I am excited to learn pyTorch!


In [4]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [12]:
vector.shape

torch.Size([2])

In [14]:
vector.ndim

1

In [15]:
matrix = torch.tensor([[7, 8], [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix.ndim

2

In [18]:
matrix.shape

torch.Size([2, 2])

In [19]:
matrix[0]

tensor([7, 8])

In [20]:
matrix[1]

tensor([ 9, 10])

In [21]:
tensor = torch.tensor([[[1, 2, 3], [3, 6, 9], [2, 5, 4]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [22]:
tensor.ndim 

3

In [23]:
tensor.shape

torch.Size([1, 3, 3])

In [24]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [26]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1336, 0.7744, 0.7646, 0.8067],
        [0.4983, 0.5083, 0.6220, 0.3872],
        [0.9061, 0.3485, 0.7679, 0.7349]])

In [27]:
random_tensor.ndim

2

In [28]:
random_tensor.shape

torch.Size([3, 4])

In [29]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))

In [30]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
ones = torch.ones(3, 4)

In [33]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
torch.arange(0, 10, 0.001)

tensor([0.0000e+00, 1.0000e-03, 2.0000e-03,  ..., 9.9970e+00, 9.9980e+00,
        9.9990e+00])

In [37]:
len(torch.arange(0, 10, 0.001))

10000

In [38]:
torch.arange(start=0, end=10, step=0.001)

tensor([0.0000e+00, 1.0000e-03, 2.0000e-03,  ..., 9.9970e+00, 9.9980e+00,
        9.9990e+00])

In [39]:
range(0, 10)

range(0, 10)

In [40]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [42]:
one_to_ten = torch.arange(1, 11, 1)

In [43]:
ten_zeros = torch.zeros_like(one_to_ten)

In [44]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])