In [2]:
import torch
import pandas as pd  
import numpy as np 
import matplotlib.pyplot as plt 


In [3]:
random_tensor = torch.rand(size=[3, 4])

In [4]:
random_tensor

tensor([[0.8483, 0.7824, 0.8421, 0.7975],
        [0.1397, 0.1142, 0.6386, 0.1027],
        [0.5361, 0.1925, 0.7530, 0.1925]])

In [5]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
one_to_ten = torch.arange(0, 11)
ten_zeros = torch.zeros_like(one_to_ten)

In [7]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
tensor = torch.tensor(data=[1, 2])
tensor

tensor([1, 2])

In [9]:
tensor

tensor([1, 2])

In [10]:
tensor / 2

tensor([0.5000, 1.0000])

In [11]:
tensor1 = torch.tensor([[2, 4, 8]])
tensor2 = torch.tensor([2, 4, 8])
tensor1 / tensor2

tensor([[1., 1., 1.]])

In [12]:
torch.matmul(tensor1, tensor2)

tensor([84])

In [13]:
tensor = tensor1.type(torch.float32)

In [14]:
tensor.mean()

tensor(4.6667)

In [15]:
torch.argmin(tensor)

tensor(0)

In [16]:
tensor.argmin()

tensor(0)

In [18]:
torch.unsqueeze(tensor, dim=0)

tensor([[[2., 4., 8.]]])

In [19]:
tensor

tensor([[2., 4., 8.]])

In [20]:
tensor.size()

torch.Size([1, 3])

In [21]:
torch.permute(tensor, [1, 0])

tensor([[2.],
        [4.],
        [8.]])